--- #YAML:1.0
name:               C-TCC
version:            0.05
abstract:           An interface to the TCC(Tiny C Compiler)
author:
    - Tsukasa Hamano <hamano@cpan.org>
license:            LGPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
